# Generated by Django 5.1.6 on 2025-02-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('senha', models.CharField(max_length=128, verbose_name='Senha')),
            ],
        ),
    ]
