# Generated by Django 5.1.6 on 2025-02-11 22:36

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='imagem',
            field=stdimage.models.StdImageField(default='path/to/default/image.jpg', force_min_size=False, upload_to='media/foto', variations={'thumb': (420, 420)}, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='senha',
            field=models.CharField(default='default_password', max_length=128, verbose_name='Senha'),
        ),
    ]
