# Generated by Django 5.1.6 on 2025-02-11 22:39

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cadastro_imagem_alter_cadastro_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='imagem',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='media/foto', variations={'thumb': (420, 420)}, verbose_name='Imagem'),
        ),
    ]
