# Generated by Django 5.1.6 on 2025-02-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_mfa_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mfa_enable',
            field=models.BooleanField(default=True),
        ),
    ]
