# Generated by Django 5.1.6 on 2025-02-22 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_mfa_enable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mfa_enable',
        ),
    ]
