# Generated by Django 5.1.6 on 2025-02-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cadastro_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='senha',
            field=models.CharField(max_length=128, verbose_name='Senha'),
        ),
    ]
