# Generated by Django 5.1.6 on 2025-02-22 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_customuser_mfa_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mfa_enable',
            field=models.BooleanField(default=False),
        ),
    ]
