# Generated by Django 5.1.6 on 2025-02-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_cadastro_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='nome',
        ),
    ]
