# Generated by Django 5.1.6 on 2025-02-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_cadastro_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='nome',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome'),
        ),
    ]
