# Generated by Django 5.1.6 on 2025-02-16 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cadastro_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='senha',
        ),
    ]
