# Generated by Django 5.1.6 on 2025-02-17 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_cadastro_email_remove_cadastro_nome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastro',
            old_name='data_nascimento',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='cadastro',
            old_name='imagem',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='cadastro',
            old_name='telefone',
            new_name='phone',
        ),
    ]
