# Generated by Django 5.1.6 on 2025-02-17 12:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_data_nascimento_cadastro_date_of_birth_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cadastro',
            new_name='Register',
        ),
    ]
